### ISSUE TITLE
Image outputs

### ISSUE THREAD

**Issue by TheodoreGalanos** [leszekhanusz/diffusion-ui-backend#12]
Can I ask where the image outputs are stored? Can they be stored if they aren't?

**Comment by leszekhanusz** [comment]
Currently images are not saved in the backend.
I made the PR #13 for this feature.

**Comment by TheodoreGalanos** [comment]
Nice thanks! I see it is merged now, will test it once in pip package (not in my computer right now to test properly).

**Comment by TheodoreGalanos** [comment]
Nvm tested, works perfectly! Thanks for adding this quickly.
