### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by db0** [leszekhanusz/diffusion-ui-backend#21]
Hey there, just checking as the integration with the AI Horde has been broken for a while now. Has this been abandoned?

**Comment by leszekhanusz** [comment]
Yes, the AI horde integration has been abandoned, there was just not enough demand for it and other alternatives appeared soon after the integration was made and had better traction.
I'm still using diffusion-ui for myself as an interface to automatic1111 for better inpainting and outpainting but that's about it.

**Comment by db0** [comment]
Gotcha. Thanks for letting me know
